// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQOTWilm17mN-cEXAUIstw9DdngXwqusY',
    appId: '1:583444395533:web:8f8d7692cd84a7fd35c744',
    messagingSenderId: '583444395533',
    projectId: 'brainboost-9363b',
    authDomain: 'brainboost-9363b.firebaseapp.com',
    storageBucket: 'brainboost-9363b.appspot.com',
    measurementId: 'G-TC3X0JSC85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQp908LMmyZnv_wi25q9bVrzEFI2g2-jE',
    appId: '1:583444395533:android:21860de7e31ed23935c744',
    messagingSenderId: '583444395533',
    projectId: 'brainboost-9363b',
    storageBucket: 'brainboost-9363b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyPgl-chiG79cEewj9h2VGF950ljzUaFk',
    appId: '1:583444395533:ios:7f5d0adb93dafcff35c744',
    messagingSenderId: '583444395533',
    projectId: 'brainboost-9363b',
    storageBucket: 'brainboost-9363b.appspot.com',
    iosBundleId: 'com.example.brainboost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyPgl-chiG79cEewj9h2VGF950ljzUaFk',
    appId: '1:583444395533:ios:4ef200509554d95835c744',
    messagingSenderId: '583444395533',
    projectId: 'brainboost-9363b',
    storageBucket: 'brainboost-9363b.appspot.com',
    iosBundleId: 'com.example.brainboost.RunnerTests',
  );
}
